# Replace these variables with your own values
TOKEN="YOUR_PERSONAL_ACCESS_TOKEN_OR_GITHUB_APP_TOKEN"
REPO="Santhosh-Nagarajan/flask-demo"
SECRET_NAME="EMAIL"
SECRET_VALUE="santhoshnagarajan6383gmai.com"

# Create the secret using the GitHub API
curl -X PUT "https://api.github.com/repos/$REPO/actions/secrets/$SECRET_NAME" \
  -H "Authorization: token $TOKEN" \
  -H "Content-Type: application/json" \
  -d '{"encrypted_value": "'"$(echo -n $SECRET_VALUE | base64)"'", "key_id": "'"$($(echo -n $PUBLIC_KEY | base64)"'"}'
